[phases.setup]
nixPkgs = ["nodejs_18", "coreutils"]

[phases.install]
# 캐시를 /tmp로만 사용하고 node_modules/.cache는 캐시하지 않음
cacheDirectories = ["/tmp/.npm", "/tmp/.cache"]
cmds = [
  "echo Node: $(node -v); echo NPM: $(npm -v)",
  "mkdir -p /tmp/.npm /tmp/.cache && chmod -R 777 /tmp/.npm /tmp/.cache",
  # 혹시 남아있는 node_modules 흔적 제거 (마운트 충돌 예방)
  "rm -rf node_modules || true",
  # 잠재적 충돌 원천 차단: 설치 스크립트는 일단 비활성화
  "npm ci --no-audit --no-fund --ignore-scripts || (npm cache clean --force && rm -rf node_modules && npm ci --no-audit --no-fund --ignore-scripts)"
]

[phases.build]
cmds = [
  # 필요한 경우에만 빌드/포스트설치 실행
  "npm run build --if-present || true",
  "npm run postinstall --if-present || true",
  "npm run postbuild --if-present || true"
]

[start]
cmd = "npm start"

