[build]
builder = "NIXPACKS"
buildCommand = "npm ci"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "emarknews"
port = 8080

[services.emarknews]
environmentVariables = [
  "NODE_ENV=production",
  "PORT=8080"
]